export const cars = [
  { id: 1, 
    name: "Maruti Suzuki Swift", 
    company: "Maruti Suzuki", 
    price: 1200, 
    type: "hatchback", 
    description: "Petrol | Seats 5 | Small boot\nThe Maruti Suzuki Swift is best for city drives, solo travelers, and small groups. This stylish, fuel-efficient hatchback offers smooth handling, reliable performance, and is perfect for weekend getaways and daily commuting.", 
    imageUrl: "/images/swift.png" },

  { id: 2, 
    name: "Hyundai i20", 
    company: "Hyundai", 
    price: 1000, 
    type: "hatchback", 
    description: "Petrol/Diesel | Seats 5 | Small boot\nThe Hyundai i20 is best for city commuting and small families. This premium hatchback offers modern features, comfortable seating, and a smooth ride, making it ideal for daily drives and weekend trips.", 
    imageUrl: "/images/i20.avif" },

  { id: 3, 
    name: "Tata Tiago", 
    company: "Tata", 
    price: 1200, 
    type: "hatchback", 
    description: "Petrol | Seats 5 | Small boot\nThe Tata Tiago is best for budget-conscious city travelers. This compact and fuel-efficient hatchback provides comfortable seating, reliable performance, and is perfect for daily commutes and short trips.", 
    imageUrl: "/images/tiago.avif" },

  { id: 4, 
    name: "Hyundai Creta", 
    company: "Hyundai", 
    price: 2000, 
    type: "SUV", 
    description: "Petrol/Diesel | Seats 5 | Medium boot\nThe Hyundai Creta is best for families and highway trips. This compact SUV offers spacious interiors, premium comfort, and advanced features, making it perfect for both city and long-distance driving.", 
    imageUrl: "/images/creta.jpg" },

  { id: 5, 
    name: "Tata Nexon", 
    company: "Tata", 
    price: 1500, 
    type: "SUV", 
    description: "Petrol/Diesel | Seats 5 | Medium boot\nThe Tata Nexon is best for city and highway drives. This safe and stylish SUV offers ample space, comfortable seating, and a smooth ride, making it ideal for families and group travel.", 
    imageUrl: "/images/nexon.jpg" },

  { id: 6, 
    name: "Maruti Suzuki Ertiga", 
    company: "Maruti Suzuki", 
    price: 2500, 
    type: "MUV", 
    description: "Petrol/CNG | Seats 7 | Large boot\nThe Maruti Suzuki Ertiga is best for family outings and group travel. This spacious MUV provides comfortable seating for seven, efficient fuel performance, and ample luggage space for long trips.", 
    imageUrl: "/images/ertiga-maruti.png" },

  { id: 7, 
    name: "Maruti Suzuki Eeco", 
    company: "Maruti Suzuki", 
    price: 1200, 
    type: "van", 
    description: "Petrol/CNG | Seats 7 | Large boot\nThe Maruti Suzuki Eeco is best for group transport and light cargo. This practical van offers flexible seating, reliable performance, and sufficient luggage space for family or small business use.", 
    imageUrl: "/images/eeco.avif" },

  { id: 8, 
    name: "Maruti Suzuki Dzire", 
    company: "Maruti Suzuki", 
    price: 1500, 
    type: "sedan", 
    description: "Petrol | Seats 5 | Medium boot\nThe Maruti Suzuki Dzire is best for city drives and highway trips. This compact sedan combines fuel efficiency, comfort, and a smooth ride, making it a popular choice for small families and couples.", 
    imageUrl: "/images/dzire.jpg" },

  { id: 9, 
    name: "Maruti Suzuki Brezza", 
    company: "Maruti Suzuki", 
    price: 1800, 
    type: "SUV", 
    description: "Petrol/Diesel | Seats 5 | Medium boot\nThe Maruti Suzuki Brezza is best for city and suburban travel. This compact SUV offers reliable performance, comfortable seating, and good fuel efficiency, making it suitable for small families and weekend trips.", 
    imageUrl: "/images/brezza.png" },

  { id: 10,
    name: "Maruti Suzuki Alto", 
    company: "Maruti Suzuki", 
    price: 900, 
    type: "hatchback", 
    description: "Petrol | Seats 5 | Small boot\nThe Maruti Suzuki Alto is best for solo travelers and couples. This affordable hatchback provides excellent fuel efficiency, easy maneuverability, and reliable city commuting performance.", 
    imageUrl: "/images/alto.jpg" },

  { id: 11, 
    name: "Hyundai Aura", 
    company: "Hyundai", 
    price: 1350, 
    type: "sedan", 
    description: "Petrol/Diesel | Seats 5 | Medium boot\nThe Hyundai Aura is best for city driving and small family trips. This stylish sedan offers modern features, comfortable seating, and ample luggage space for daily and weekend travel.", 
    imageUrl: "/images/aura.avif" },

  { id: 12, 
    name: "Hyundai Venue", 
    company: "Hyundai", 
    price: 1700, 
    type: "SUV", 
    description: "Petrol/Diesel | Seats 5 | Medium boot\nThe Hyundai Venue is best for urban commuting and short highway trips. This feature-rich compact SUV combines comfort, space, and modern tech, ideal for young travelers and small families.", 
    imageUrl: "/images/venue.png" },

  { id: 13, 
    name: "Toyota Innova", 
    company: "Toyota", 
    price: 3000, 
    type: "MUV", 
    description: "Petrol/Diesel | Seats 7-8 | Large boot\nThe Toyota Innova is best for large families and group travel. This premium MUV offers spacious interiors, comfortable seating, and smooth performance, making it perfect for long trips and vacations.", 
    imageUrl: "/images/innova.avif" },

  { id: 14, 
    name: "Mahindra Bolero", 
    company: "Mahindra", 
    price: 2100, 
    type: "SUV", 
    description: "Diesel | Seats 7 | Large boot\nThe Mahindra Bolero is best for rugged terrains and rural drives. This strong and spacious SUV provides reliable performance, ample seating, and durability, making it ideal for adventure and daily travel.", 
    imageUrl: "/images/bolero-mahindra.jpg" },

  { id: 15, 
    name: "Mahindra Scorpio", 
    company: "Mahindra", 
    price: 2500, 
    type: "SUV", 
    description: "Diesel | Seats 7 | Large boot\nThe Mahindra Scorpio is best for city and highway trips with groups. This powerful SUV offers bold styling, spacious interiors, and excellent performance, making it suitable for families and adventure trips.", 
    imageUrl: "/images/scorpio.avif"},

  { id: 16, 
    name: "Mahindra Thar Roxx", 
    company: "Mahindra", 
    price: 2700, 
    type: "SUV", 
    description: "Diesel | Seats 4 | Medium boot\nThe Mahindra Thar Roxx is best for off-road adventures and weekend trips. This rugged SUV with a convertible roof offers thrill, comfort, and reliable performance for small groups of adventure seekers.", 
    imageUrl: "/images/thar-roxx.avif" },
]

